version: "3"

services:
  backend:
    image: sample-app:backend
    build:
      context: .
    ports:
      - 8080:8080
    networks:
      - default
      - backend
    # environment:
    expose:
      - 8080

networks:
  backend: